### ISSUE TITLE
Unable to scroll and grey screen in web preview

### ISSUE THREAD

**Issue by Rgada28** [Harshit2756/Flutter_ticket_app#1]
- Unable to scroll in web preview using a mouse, was able to scroll using touchpad though
- Grey screen issues when navigating to view all hotel and click on any hotel results to grey screen
https://github.com/user-attachments/assets/d95df195-1596-4ec0-a0e2-cdb3a2e8cb3c

**Comment by Harshit2756** [comment]
the issue has been resolved
